export const CREATE_DATA= "CREATE_DATA"
export const READ_ALL_DATA=  "READ_ALL_DATA"
export const READ_ITEM_DATA=  "READ_ITEM_DATA"
export const UPDATE_DATA=  "UPDATE_DATA"
export const DELETE_DATA=  "DELETE_DATA"
export const NO_DATA=  "NO_DATA"
export const initPosts=  "initPosts"
